import { v } from "convex/values";
import { internal } from "./_generated/api";
import { internalMutation } from "./_generated/server";
import type { MutationCtx } from "./_generated/server";
import type { Id } from "./_generated/dataModel";
import { assertTransition } from "../src/orchestrator/state-machine";
import type { DiagnosisOutput } from "../src/orchestrator/contracts";
import { diagnosisValidator } from "./diagnosis_contract";

type SuccessArgs={incidentId:Id<"incidents">;runId:Id<"agentRuns">;diagnosis:DiagnosisOutput;model:string;tokens?:number;cost?:number;durationMs?:number};
const publicReasons=new Set(["MODEL_CONFIGURATION_UNAVAILABLE","MODEL_HTTP_FAILURE","INVALID_MODEL_ENVELOPE","MALFORMED_MODEL_JSON","INVALID_DIAGNOSIS"]);

async function transition(ctx:MutationCtx,incidentId:Id<"incidents">,to:"PLANNING"|"DIAGNOSING"|"DIAGNOSIS_REVIEW"|"ESCALATED",runId?:Id<"agentRuns">,metadata:Record<string,unknown>={}){const incident=await ctx.db.get(incidentId);if(!incident)throw new Error("INCIDENT_NOT_FOUND");assertTransition(incident.status,to);await ctx.db.patch(incidentId,{status:to,awaitingApproval:false});await ctx.db.insert("events",{incidentId,runId,type:"STATE_TRANSITION",status:to,timestamp:Date.now(),metadata:{from:incident.status,...metadata}})}

export const start=internalMutation({args:{incidentId:v.id("incidents")},handler:async(ctx,{incidentId})=>{const incident=await ctx.db.get(incidentId);if(!incident||incident.effectiveMode!=="INVESTIGATE_ONLY"||incident.status!=="DETECTED")return null;const existing=await ctx.db.query("agentRuns").withIndex("by_incident",q=>q.eq("incidentId",incidentId)).take(10);if(existing.some(r=>r.agent==="DIAGNOSER"))return null;const now=Date.now();const commander=await ctx.db.insert("agentRuns",{incidentId,agent:"COMMANDER",status:"succeeded",inputSummary:"Plan investigate-only incident",outputSummary:"Deterministic investigation plan persisted",idempotencyKey:`${incident.idempotencyKey}:commander`,promptVersion:"investigate-only-v1",queuedAt:now,startedAt:now,finishedAt:now});await ctx.db.insert("orchestrationPlans",{incidentId,runId:commander,steps:["Inspect incident context","Request one structured diagnosis","Review and escalate with handoff"],createdAt:now});await transition(ctx,incidentId,"PLANNING",commander);await transition(ctx,incidentId,"DIAGNOSING",commander);const diagnoser=await ctx.db.insert("agentRuns",{incidentId,agent:"DIAGNOSER",parentRunId:commander,status:"running",inputSummary:"Produce strict structured diagnosis",idempotencyKey:`${incident.idempotencyKey}:diagnoser`,promptVersion:"investigate-only-v1",queuedAt:now,startedAt:now});await ctx.db.patch(incidentId,{attempts:{...incident.attempts,diagnosis:incident.attempts.diagnosis+1}});await ctx.scheduler.runAfter(0,internal.diagnoser.callModel,{incidentId,runId:diagnoser});return diagnoser;}});

async function persistSuccess(ctx:MutationCtx,args:SuccessArgs){if(args.diagnosis.rootCause.length===0||args.diagnosis.confidence<0||args.diagnosis.confidence>1||args.diagnosis.evidence.length<2)throw new Error("INVALID_DIAGNOSIS");const incident=await ctx.db.get(args.incidentId);const run=await ctx.db.get(args.runId);if(!incident||!run||run.incidentId!==args.incidentId||run.agent!=="DIAGNOSER")throw new Error("STALE_COMPLETION");if(run.status!=="running")return null;if(incident.status!=="DIAGNOSING")throw new Error("STALE_COMPLETION");const existing=await ctx.db.query("diagnoses").withIndex("by_incident",q=>q.eq("incidentId",args.incidentId)).unique();if(existing)return existing._id;const now=Date.now();const diagnosisId=await ctx.db.insert("diagnoses",{incidentId:args.incidentId,runId:args.runId,rootCause:args.diagnosis.rootCause,confidence:args.diagnosis.confidence,affectedSurfaces:args.diagnosis.affectedSurfaces,risk:args.diagnosis.risk,recommendedRepair:args.diagnosis.recommendedRepair,requiredFiles:args.diagnosis.requiredFiles,dependencyChange:args.diagnosis.dependencyChange,migrationChange:args.diagnosis.migrationChange,secretChange:args.diagnosis.secretChange,createdAt:now});for(const evidence of args.diagnosis.evidence)await ctx.db.insert("diagnosisEvidence",{incidentId:args.incidentId,diagnosisId,...evidence,createdAt:now});await ctx.db.patch(args.runId,{status:"succeeded",outputSummary:args.diagnosis.rootCause,model:args.model,tokens:args.tokens,cost:args.cost,durationMs:args.durationMs,finishedAt:now});await transition(ctx,args.incidentId,"DIAGNOSIS_REVIEW",args.runId);const review=await ctx.db.insert("agentRuns",{incidentId:args.incidentId,agent:"COMMANDER",parentRunId:args.runId,status:"succeeded",inputSummary:"Review diagnosis for investigate-only handoff",outputSummary:"Diagnosis accepted for human escalation; no repair attempted",idempotencyKey:`${incident.idempotencyKey}:review`,promptVersion:"investigate-only-v1",queuedAt:now,startedAt:now,finishedAt:now});await ctx.db.patch(args.incidentId,{rootCause:args.diagnosis.rootCause,confidence:args.diagnosis.confidence,resolutionSummary:`Investigation complete: ${args.diagnosis.rootCause}. Recommended next step: ${args.diagnosis.recommendedRepair}. No repair or deployment was attempted.`});await transition(ctx,args.incidentId,"ESCALATED",review,{handoff:"Human action required"});return diagnosisId;}

export const persistModelSuccess=internalMutation({args:{incidentId:v.id("incidents"),runId:v.id("agentRuns"),diagnosis:diagnosisValidator,model:v.string(),tokens:v.optional(v.number()),cost:v.optional(v.number()),durationMs:v.optional(v.number())},handler:persistSuccess});
export const failClosed=internalMutation({args:{incidentId:v.id("incidents"),runId:v.id("agentRuns"),reason:v.string(),durationMs:v.optional(v.number())},handler:async(ctx,args)=>{const incident=await ctx.db.get(args.incidentId);const run=await ctx.db.get(args.runId);if(!incident||!run||run.incidentId!==args.incidentId||run.agent!=="DIAGNOSER")throw new Error("STALE_COMPLETION");if(run.status!=="running")return null;if(incident.status!=="DIAGNOSING")throw new Error("STALE_COMPLETION");const reason=publicReasons.has(args.reason)?args.reason:"INVALID_DIAGNOSIS";const now=Date.now();await ctx.db.patch(args.runId,{status:"failed",outputSummary:reason,durationMs:args.durationMs,finishedAt:now});await ctx.db.insert("events",{incidentId:args.incidentId,runId:args.runId,type:"DIAGNOSIS_FAILURE",status:"FAILED",timestamp:now,metadata:{reason}});await transition(ctx,args.incidentId,"DIAGNOSIS_REVIEW",args.runId,{failure:true});const review=await ctx.db.insert("agentRuns",{incidentId:args.incidentId,agent:"COMMANDER",parentRunId:args.runId,status:"succeeded",inputSummary:"Review failed diagnosis attempt",outputSummary:"Escalated without diagnosis",idempotencyKey:`${incident.idempotencyKey}:review-failure`,promptVersion:"investigate-only-v1",queuedAt:now,startedAt:now,finishedAt:now});await ctx.db.patch(args.incidentId,{resolutionSummary:`${reason}. No diagnosis was fabricated and no repair or deployment was attempted.`});await transition(ctx,args.incidentId,"ESCALATED",review,{failure:true});return null;}});
