/// <reference types="vite/client" />
import { convexTest } from "convex-test";
import { afterEach, beforeEach, describe, expect, test, vi } from "vitest";
import { api, internal } from "./_generated/api";
import { diagnosisValidator } from "./diagnosis-contract";
import { diagnosisOutput } from "../src/orchestrator/contracts";
import schema from "./schema";
const modules=import.meta.glob("./**/*.ts");
const evidence=[{source:"log" as const,summary:"503 observed",ref:"request:r1"},{source:"code" as const,summary:"Pool controls connections",ref:"src/db.ts"}];
const diagnosis={rootCause:"Database pool exhaustion",confidence:.86,evidence,affectedSurfaces:["checkout API"],risk:"medium" as const,recommendedRepair:"Inspect pool sizing",requiredFiles:["src/db.ts"],dependencyChange:false,migrationChange:false,secretChange:false};
const forbiddenStatuses=["PATCHING","PATCH_REVIEW","PR_READY","AWAITING_APPROVAL","DEPLOYING","VERIFYING","PERF_CHECK","ASSIGNEE_SELECTION","HANDOFF_READY","RETRYING","ROLLING_BACK","RESOLVED"];
function expectNoForbiddenSideEffects(detail:{deployments:unknown[];verifications:unknown[];performance:unknown[];approvals:unknown[];events:Array<{status:string}>}){expect(detail.deployments).toEqual([]);expect(detail.verifications).toEqual([]);expect(detail.performance).toEqual([]);expect(detail.approvals).toEqual([]);expect(detail.events.filter(event=>forbiddenStatuses.includes(event.status))).toEqual([])}
async function fixture(t:ReturnType<typeof convexTest>,profile=true){const projectId=await t.run(ctx=>ctx.db.insert("projects",{name:"Tracer",owner:"team",repo:"team/tracer",defaultBranch:"main",productionUrl:"https://example.com",cloudflareProject:"tracer",defaultMode:"INVESTIGATE_ONLY",guardrails:{},verificationConfig:{},baselineLatencyMs:500,createdAt:Date.now()}));if(profile)await t.run(ctx=>ctx.db.insert("modelProfiles",{agent:"DIAGNOSER",kind:"llm",provider:"compatible",model:"test-model",temperature:0,maxTokens:1000,promptVersion:"v1",enabled:true,updatedAt:Date.now()}));const incidentId=await t.run(async ctx=>{const id=await ctx.db.insert("incidents",{projectId,source:"dashboard",service:"api",severity:"SEV2",configuredMode:"INVESTIGATE_ONLY",effectiveMode:"INVESTIGATE_ONLY",status:"DETECTED",startedAt:Date.now(),awaitingApproval:false,attempts:{diagnosis:0,patch:0,verification:0},deadlineAt:Date.now()+60000,budgetUsd:1,idempotencyKey:crypto.randomUUID()});await ctx.db.insert("events",{incidentId:id,type:"STATE_TRANSITION",status:"DETECTED",timestamp:Date.now(),metadata:{}});return id});await t.run(ctx=>ctx.db.insert("logs",{projectId,timestamp:1,endpoint:"/checkout",method:"POST",status:503,latency:900,error:"pool timeout Bearer super-secret?token=query-secret",requestId:"r1",version:"abc"}));const runId=await t.mutation(internal.orchestration.start,{incidentId});if(!runId)throw new Error("missing run");return {incidentId,runId};}
function response(content:unknown,ok=true){return {ok,status:ok?200:500,json:async()=>content} as Response}
beforeEach(()=>vi.useFakeTimers());
afterEach(()=>{vi.useRealTimers();vi.unstubAllGlobals();delete process.env.DIAGNOSER_API_KEY;delete process.env.DIAGNOSER_BASE_URL});

describe("authoritative diagnosis contract",()=>{
 test("the shared Convex validator accepts exactly values accepted by diagnosisOutput",()=>{expect(diagnosisOutput.parse(diagnosis)).toEqual(diagnosis);expect(diagnosisValidator).toBeDefined()});
});

describe("investigate-only production action",()=>{
 test("constructs contextual request, parses envelope and usage, fetches exactly once, and persists structured result",async()=>{const t=convexTest(schema,modules);const {incidentId,runId}=await fixture(t);process.env.DIAGNOSER_API_KEY="secret";process.env.DIAGNOSER_BASE_URL="https://provider.example/v1";const fetchMock=vi.fn(async(_url:string,init?:RequestInit)=>response({choices:[{message:{content:JSON.stringify(diagnosis)}}],usage:{total_tokens:123,cost_usd:.02}}));vi.stubGlobal("fetch",fetchMock);await t.action(internal.diagnoser.callModel,{incidentId,runId});expect(fetchMock).toHaveBeenCalledTimes(1);const request=JSON.parse(String(fetchMock.mock.calls[0][1]?.body));expect(request.messages[1].content).toContain('"service":"api"');expect(request.messages[1].content).toContain('"repo":"team/tracer"');expect(request.messages[1].content).toContain('"status":503');const detail=await t.query(api.dashboard.incidentDetail,{incidentId});expect(detail?.incident.status).toBe("ESCALATED");expect(detail?.diagnosisEvidence).toMatchObject(evidence);expect(detail?.runs.find(r=>r.agent==="DIAGNOSER")).toMatchObject({tokens:123,cost:.02});expect(detail?.events.filter(e=>e.type==="STATE_TRANSITION").map(e=>e.status)).toEqual(["DETECTED","PLANNING","DIAGNOSING","DIAGNOSIS_REVIEW","ESCALATED"]);expectNoForbiddenSideEffects(detail!)});
 test("redacts log credentials before sending model context",async()=>{const t=convexTest(schema,modules);const {incidentId,runId}=await fixture(t);process.env.DIAGNOSER_API_KEY="secret";process.env.DIAGNOSER_BASE_URL="https://provider.example/v1";const fetchMock=vi.fn(async(_url:string,init?:RequestInit)=>response({choices:[{message:{content:JSON.stringify(diagnosis)}}]}));vi.stubGlobal("fetch",fetchMock);await t.action(internal.diagnoser.callModel,{incidentId,runId});const body=String(fetchMock.mock.calls[0][1]?.body);expect(body).not.toContain("super-secret");expect(body).not.toContain("query-secret");expect(body).toContain("[REDACTED]")});
 test.each([["malformed envelope",{}],["malformed JSON",{choices:[{message:{content:"{"}}]}],["invalid diagnosis",{choices:[{message:{content:JSON.stringify({...diagnosis,rootCause:""})}}]}]])("%s fails closed without diagnosis",async(_name,body)=>{const t=convexTest(schema,modules);const {incidentId,runId}=await fixture(t);process.env.DIAGNOSER_API_KEY="x";process.env.DIAGNOSER_BASE_URL="https://x";const fetchMock=vi.fn(async()=>response(body));vi.stubGlobal("fetch",fetchMock);await t.action(internal.diagnoser.callModel,{incidentId,runId});const detail=await t.query(api.dashboard.incidentDetail,{incidentId});expect(fetchMock).toHaveBeenCalledTimes(1);expect(detail?.diagnosis).toBeNull();expect(detail?.incident.status).toBe("ESCALATED");expect(detail?.incident.resolutionSummary).not.toContain("https://x");expectNoForbiddenSideEffects(detail!)});
 test("HTTP failure is sanitized and has no side effects",async()=>{const t=convexTest(schema,modules);const {incidentId,runId}=await fixture(t);process.env.DIAGNOSER_API_KEY="x";process.env.DIAGNOSER_BASE_URL="https://x";vi.stubGlobal("fetch",vi.fn(async()=>response({secret:"leak"},false)));await t.action(internal.diagnoser.callModel,{incidentId,runId});const d=await t.query(api.dashboard.incidentDetail,{incidentId});expect(d?.incident.resolutionSummary).toContain("MODEL_HTTP_FAILURE");expect(d?.incident.resolutionSummary).not.toContain("leak");expect(d?.deployments).toEqual([])});
 test("missing or disabled profile performs no fetch",async()=>{const t=convexTest(schema,modules);const {incidentId,runId}=await fixture(t,false);process.env.DIAGNOSER_API_KEY="x";process.env.DIAGNOSER_BASE_URL="https://x";const f=vi.fn();vi.stubGlobal("fetch",f);await t.action(internal.diagnoser.callModel,{incidentId,runId});expect(f).not.toHaveBeenCalled();expect((await t.query(api.dashboard.incidentDetail,{incidentId}))?.incident.status).toBe("ESCALATED")});
 test("duplicate success completion is idempotent",async()=>{const t=convexTest(schema,modules);const {incidentId,runId}=await fixture(t);const args={incidentId,runId,diagnosis,model:"m"};await t.mutation(internal.orchestration.persistModelSuccess,args);await t.mutation(internal.orchestration.persistModelSuccess,args);const d=await t.query(api.dashboard.incidentDetail,{incidentId});expect(d?.diagnosisEvidence).toHaveLength(2);expect(d?.runs.filter(r=>r.agent==="COMMANDER")).toHaveLength(2);expect(d?.events.filter(e=>e.status==="ESCALATED")).toHaveLength(1)});
});

describe("investigate-only scheduler end to end",()=>{
 test.each([{name:"success",body:{choices:[{message:{content:JSON.stringify(diagnosis)}}]},hasDiagnosis:true},{name:"representative failure",body:{choices:[{message:{content:"{"}}]},hasDiagnosis:false}])("api create automatically follows the exact $name path once",async({body,hasDiagnosis})=>{const t=convexTest(schema,modules);const projectId=await t.run(ctx=>ctx.db.insert("projects",{name:"E2E",owner:"team",repo:"team/e2e",defaultBranch:"main",productionUrl:"https://example.com",cloudflareProject:"e2e",defaultMode:"INVESTIGATE_ONLY",guardrails:{},verificationConfig:{},baselineLatencyMs:500,createdAt:Date.now()}));await t.run(ctx=>ctx.db.insert("modelProfiles",{agent:"DIAGNOSER",kind:"llm",provider:"compatible",model:"test-model",temperature:0,maxTokens:1000,promptVersion:"v1",enabled:true,updatedAt:Date.now()}));process.env.DIAGNOSER_API_KEY="x";process.env.DIAGNOSER_BASE_URL="https://provider.example/v1";const fetchMock=vi.fn(async()=>response(body));vi.stubGlobal("fetch",fetchMock);const incidentId=await t.mutation(api.incidents.create,{projectId,source:"dashboard",service:"api",severity:"SEV2",configuredMode:"INVESTIGATE_ONLY",idempotencyKey:`e2e-${hasDiagnosis}`});await t.finishAllScheduledFunctions(vi.runAllTimers);const detail=await t.query(api.dashboard.incidentDetail,{incidentId});expect(fetchMock).toHaveBeenCalledTimes(1);expect(detail?.runs.filter(run=>run.agent==="DIAGNOSER")).toHaveLength(1);expect(detail?.events.filter(event=>event.type==="STATE_TRANSITION").map(event=>event.status)).toEqual(["DETECTED","PLANNING","DIAGNOSING","DIAGNOSIS_REVIEW","ESCALATED"]);expect(Boolean(detail?.diagnosis)).toBe(hasDiagnosis);expectNoForbiddenSideEffects(detail!)});
});
