import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";
const mode=v.union(v.literal("AUTO_RESOLVE"),v.literal("PR_APPROVAL"),v.literal("INVESTIGATE_ONLY"));
const incidentStatus=v.union(...["DETECTED","PLANNING","DIAGNOSING","DIAGNOSIS_REVIEW","PATCHING","PATCH_REVIEW","PR_READY","AWAITING_APPROVAL","DEPLOYING","VERIFYING","PERF_CHECK","ASSIGNEE_SELECTION","HANDOFF_READY","RETRYING","ROLLING_BACK","RESOLVED","ESCALATED"].map(x=>v.literal(x)) as [any,...any[]]);
export default defineSchema({
 projects:defineTable({name:v.string(),owner:v.string(),repo:v.string(),defaultBranch:v.string(),productionUrl:v.string(),cloudflareProject:v.string(),defaultMode:mode,guardrails:v.any(),verificationConfig:v.any(),baselineLatencyMs:v.number(),createdAt:v.number()}).index("by_repo",["repo"]),
 modelProfiles:defineTable({agent:v.string(),kind:v.union(v.literal("llm"),v.literal("deterministic")),provider:v.optional(v.string()),model:v.optional(v.string()),temperature:v.optional(v.number()),maxTokens:v.optional(v.number()),promptVersion:v.string(),enabled:v.boolean(),updatedAt:v.number()}).index("by_agent",["agent"]),
 incidents:defineTable({projectId:v.id("projects"),source:v.union(v.literal("voice"),v.literal("telegram"),v.literal("auto_detect"),v.literal("dashboard"),v.literal("webhook")),service:v.string(),severity:v.union(v.literal("SEV1"),v.literal("SEV2"),v.literal("SEV3")),configuredMode:mode,effectiveMode:mode,status:incidentStatus,startedAt:v.number(),resolvedAt:v.optional(v.number()),rootCause:v.optional(v.string()),confidence:v.optional(v.number()),resolutionSummary:v.optional(v.string()),awaitingApproval:v.boolean(),approvedBy:v.optional(v.string()),attempts:v.object({diagnosis:v.number(),patch:v.number(),verification:v.number()}),deadlineAt:v.number(),budgetUsd:v.number(),idempotencyKey:v.string()}).index("by_project_status",["projectId","status"]).index("by_idempotency",["idempotencyKey"]),
 agentRuns:defineTable({incidentId:v.id("incidents"),agent:v.string(),parentRunId:v.optional(v.id("agentRuns")),status:v.union(v.literal("queued"),v.literal("running"),v.literal("succeeded"),v.literal("failed"),v.literal("rejected")),inputSummary:v.string(),outputSummary:v.optional(v.string()),idempotencyKey:v.optional(v.string()),provider:v.optional(v.string()),model:v.optional(v.string()),promptVersion:v.optional(v.string()),tokens:v.optional(v.number()),cost:v.optional(v.number()),durationMs:v.optional(v.number()),queuedAt:v.optional(v.number()),startedAt:v.optional(v.number()),finishedAt:v.optional(v.number()),errorCode:v.optional(v.string()),rejectionReason:v.optional(v.string())}).index("by_incident",["incidentId"]),
 orchestrationPlans:defineTable({incidentId:v.id("incidents"),runId:v.id("agentRuns"),steps:v.array(v.string()),createdAt:v.number()}).index("by_incident",["incidentId"]),
 diagnoses:defineTable({incidentId:v.id("incidents"),runId:v.id("agentRuns"),rootCause:v.string(),confidence:v.number(),affectedSurfaces:v.array(v.string()),risk:v.string(),recommendedRepair:v.string(),requiredFiles:v.array(v.string()),dependencyChange:v.boolean(),migrationChange:v.boolean(),secretChange:v.boolean(),createdAt:v.number()}).index("by_incident",["incidentId"]),
 diagnosisEvidence:defineTable({incidentId:v.id("incidents"),diagnosisId:v.id("diagnoses"),source:v.union(v.literal("log"),v.literal("deployment"),v.literal("commit"),v.literal("code"),v.literal("runbook"),v.literal("research")),summary:v.string(),ref:v.string(),createdAt:v.number()}).index("by_incident",["incidentId"]),
 events:defineTable({incidentId:v.id("incidents"),runId:v.optional(v.id("agentRuns")),type:v.string(),tool:v.optional(v.string()),status:v.string(),timestamp:v.number(),metadata:v.any()}).index("by_incident_time",["incidentId","timestamp"]),
 deployments:defineTable({incidentId:v.id("incidents"),branch:v.string(),commitSha:v.string(),previewUrl:v.optional(v.string()),productionUrl:v.optional(v.string()),status:v.string(),startedAt:v.number(),readyAt:v.optional(v.number()),externalDeploymentId:v.string()}).index("by_incident",["incidentId"]),
 verifications:defineTable({incidentId:v.id("incidents"),deploymentId:v.id("deployments"),request:v.any(),responseStatus:v.number(),latencyMs:v.number(),assertions:v.any(),passed:v.boolean(),freshLogsClean:v.boolean(),logsCheckedAt:v.number(),verifiedAt:v.number()}).index("by_incident",["incidentId"]),
 performance:defineTable({incidentId:v.id("incidents"),deploymentId:v.id("deployments"),baselineP95Ms:v.number(),postFixP50Ms:v.number(),postFixP95Ms:v.number(),successRate:v.number(),samples:v.number(),verdict:v.union(v.literal("PASS"),v.literal("REGRESSION"),v.literal("WAIVED")),note:v.optional(v.string()),measuredAt:v.number()}).index("by_incident",["incidentId"]),
 runbooks:defineTable({projectId:v.id("projects"),symptoms:v.array(v.string()),errorSignature:v.string(),rootCause:v.string(),fixSummary:v.string(),verificationSummary:v.string(),successCount:v.number(),avgResolutionMs:v.number(),embedding:v.optional(v.array(v.float64())),createdAt:v.number(),lastUsedAt:v.number()}).index("by_project_signature",["projectId","errorSignature"]),
 approvals:defineTable({incidentId:v.id("incidents"),type:v.literal("DEPLOY"),status:v.union(v.literal("PENDING"),v.literal("APPROVED"),v.literal("REJECTED"),v.literal("EXPIRED")),requestedAt:v.number(),decidedAt:v.optional(v.number()),decisionBy:v.optional(v.string()),notes:v.optional(v.string())}).index("by_incident",["incidentId"]),
 evalCases:defineTable({name:v.string(),failureMode:v.string(),expectedCause:v.string(),allowedFiles:v.array(v.string()),expectedAssertions:v.array(v.string()),status:v.union(v.literal("ACTIVE"),v.literal("DISABLED")),createdAt:v.number()}).index("by_name",["name"]),
 evalRuns:defineTable({evalCaseId:v.id("evalCases"),promptVersion:v.string(),agentVersion:v.string(),passed:v.boolean(),invariantResults:v.any(),durationMs:v.number(),costUsd:v.number(),createdAt:v.number()}).index("by_case_time",["evalCaseId","createdAt"]),
 logs:defineTable({timestamp:v.number(),endpoint:v.string(),method:v.string(),status:v.number(),latency:v.number(),error:v.optional(v.string()),requestId:v.string(),version:v.string(),projectId:v.optional(v.id("projects"))}).index("by_project_time",["projectId","timestamp"]).index("by_status_time",["status","timestamp"])
});
